hpc=read.table("household_power_consumption.txt",skip=66636,nrows=2880,stringsAsFactors=FALSE,header=TRUE,sep=";",col.names=c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
x=paste(hpc$Date,hpc$Time,sep=" ")
x=strptime(x,"%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
plot(x,hpc$Global_active_power,xlab="",type="l",ylab="Global Active Power (kilowatts)")
plot(x,hpc$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(x,hpc$Sub_metering_1,xlab="",type="l",ylab="Energy sub metering")
lines(x,hpc$Sub_metering_2,col=2)
lines(x,hpc$Sub_metering_3,col=4)
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c(1,2,4),lty=1,cex=0.8)
plot(x,hpc$Global_reactive_power,xlab="datetime",type="l")
